server:
  port: 8081
  servlet:
    context-path: /2020

jasypt:
  encryptor:
    password: SecretKey # jasypt 密钥；为防止密钥泄露，可以在项目部署时用命令传入秘钥值：java -jar -Djasypt.encryptor.password=SecretKey xxx.jar（还可以在服务器环境变量里配置，进一步提高安全性）
    algorithm: PBEWithMD5AndDES # 默认加密方式 PBEWithMD5AndDES，可以更改为 PBEWithMD5AndTripleDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator # jasypt 在 3.0.0 以后更改了加密算法，需要增加此配置，否则启动会报错（使用低于 3.0.0 版本可不配置此项）

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springboot-2020?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: ENC(6YrBrC3DIPDhLs6pDblobg==) # 使用 jasypt 加密
    password: ENC(ZtkRoI6NnmHAhN8USO1DDA==) # 使用 jasypt 加密
#  devtools:
#    restart:
#      enabled: true # 配置项目热部署（SpringBoot不配置也生效，只需要pom文件中的热部署配置）
  jpa:
    show-sql: true
  redis:
    database: 1 # Redis数据库索引（默认为0），如果设置为1，那么存入的key-value都存放在select 1中
    host: 127.0.0.1
    port: 6379
    max-wait: 30000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
    max-active: 100 # 连接池最大连接数（使用负值表示没有限制）
    max-idle: 20    # 连接池中的最大空闲连接
    min-idle: 0     # 连接池中的最小空闲连接
    timeout: 5000   # 连接超时
#    password:       # 密码，默认密码为空
#    cluster:        # 集群配置
#    nodes: 127.0.0.1:6381,127.0.0.1:6382,127.0.0.1:6383,127.0.0.1:6384,127.0.0.1:6385,127.0.0.1:6386
#    max-redirects: 2 # 最大重定向次数
  #rabbitmq
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest

mybatis:
  mapper-locations: classpath:mapper/*.xml

local:
  develop: true
